version: v1

payload_fields:
  request_id:
    path: "$.payload.request_id"
    type: STRING

  customer_id:
    path: "$.payload.customer_id"
    type: STRING

  request_type:
    path: "$.payload.request_type"
    type: STRING

  priority:
    path: "$.payload.priority"
    type: STRING

  location:
    path: "$.payload.location"
    type: STRING

  description:
    path: "$.payload.description"
    type: STRING

  source_system:
    path: "$.payload.source_system"
    type: STRING

#this file can be changes based on requirements/scenario